spring:
  profiles:
    active: remote
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.34.50:3306/cardb?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Wave123.
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080
  servlet:
    context-path: /oldcar

